IC-Prod/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Users can create these types for prospect accounts.  Once the prospect becomes a customer, this information should be merged with the real customer account.  Only managers and above can merge.</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

IC-Prod/objects/Account_Reassignment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>Account__r.RecordType.Name</formula>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Reassignments</relationshipLabel>
        <relationshipName>Account_Reassignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Statuses will dynamically change depending on stage in the Approval process</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Reassignment</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Account Reassignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Reassignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IC-Prod/classes/AccountReassignment_Utilities.cls
public with sharing class AccountReassignment_Utilities
{
	public static void AccountReassignmentAfterUpdate(List<sObject> accountReassignments, Map<Id, sObject> oldMap)
	{
		SetNewOwnerForProspectAccountsOnApproved((List<Account_Reassignment__c>)accountReassignments, (Map<Id, Account_Reassignment__c>)oldMap);
	}
	
	public static void SetNewOwnerForProspectAccountsOnApproved(List<Account_Reassignment__c> accountReassignments, Map<Id, Account_Reassignment__c> oldMap)
	{
		List<Account> accountsToUpdateOwner = new List<Account>();
		
		for (Account_Reassignment__c ar : accountReassignments)
		{
			//Account is Prospect and Status__c changed to Approved
			if (ar.Account_Type__c == 'Prospect' && ar.Status__c == 'Approved' && oldMap.get(ar.Id).Status__c != 'Approved')
			{
				accountsToUpdateOwner.add(new Account(Id = ar.Account__c, OwnerId = ar.New_Owner__c));
			}
		}
		
		if (accountsToUpdateOwner.size() > 0) { Database.update(accountsToUpdateOwner); }
	}
}