IC-Prod/objects/Customer_Account_Plan__c.object
<CustomObject>
    <description>Related to Account object.  New version created at each save.</description>
    <fields>
        <fullName>Net_Readiness_Score__c</fullName>
        <description>Formula based on Section 3: Opportunity Qualification Scorecard answers.</description>
        <formula>0+ CASE(Significant_current_or_potential_spend__c, &quot;Yes&quot;, +2, &quot;No&quot;, -2, &quot;Unknown&quot;, +0, 0) +
CASE(Financially_healthy_organization__c, &quot;Yes&quot;, +2, &quot;No&quot;, -2, &quot;Unknown&quot;, +0, 0) +
CASE(External_pressures_to_change__c, &quot;Yes&quot;, +3, &quot;No&quot;, -3, &quot;Unknown&quot;, +0, 0) +
CASE(Internal_pressures_to_change__c, &quot;Yes&quot;, +3, &quot;No&quot;, -3, &quot;Unknown&quot;, +0, 0) +
CASE(Organization_wide_discontent__c, &quot;Yes&quot;, +4, &quot;No&quot;, -4, &quot;Unknown&quot;, +0, 0) +
CASE(Current_supplier_falls_short__c, &quot;Yes&quot;, +4, &quot;No&quot;, -4, &quot;Unknown&quot;, +0, 0) +
CASE(Dissatisfaction_with_existing_solutions__c, &quot;Yes&quot;, +4, &quot;No&quot;, -4, &quot;Unknown&quot;, +0, 0) +
CASE(General_organizational_needs_unmet__c, &quot;Yes&quot;, +4, &quot;No&quot;, -4, &quot;Unknown&quot;, +0, 0) +
CASE(Frequent_sharing_of_best_practices__c, &quot;Yes&quot;, +6, &quot;No&quot;, -6, &quot;Unknown&quot;, +0, 0) +
CASE(Multiple_stakeholders_learning__c, &quot;Yes&quot;, +6, &quot;No&quot;, -6, &quot;Unknown&quot;, +0, 0) +
CASE(Senior_leaders_reach_out_for_ideas__c, &quot;Yes&quot;, +6, &quot;No&quot;, -6, &quot;Unknown&quot;, +0, 0) +
CASE(Improvement_initiatives_as_ongoing__c, &quot;Yes&quot;, +6, &quot;No&quot;, -6, &quot;Unknown&quot;, +0, 0) +
CASE(Engages_in_constructive_dialogue__c, &quot;Yes&quot;, +10, &quot;No&quot;, -10, &quot;Unknown&quot;, +0, 0) +
CASE(Articulate_differences_current_vs_new__c, &quot;Yes&quot;, +10, &quot;No&quot;, -10, &quot;Unknown&quot;, +0, 0) +
CASE(Request_continuing_conversations__c, &quot;Yes&quot;, +10, &quot;No&quot;, -10, &quot;Unknown&quot;, +0, 0) +
CASE(Express_openness_to_escalation__c, &quot;Yes&quot;, +10, &quot;No&quot;, -10, &quot;Unknown&quot;, +0, 0) +
CASE(Mobilizers_exist__c, &quot;Yes&quot;, +10, &quot;No&quot;, -10, &quot;Unknown&quot;, +0, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This value is calculated based on Section 3: Opportunity Qualification Scorecard&apos;s values.</inlineHelpText>
        <label>Net Readiness Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <formula>Account__r.OwnerLink__r.FirstName + &quot; &quot; +  Account__r.OwnerLink__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the SFDC User record corresponding to the Sales Manager from UVX.  Populated by Apex trigger which looks up the User by alias, using the Sales Mgr Id from UVX.</description>
        <label>Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Account_Plans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMName__c</fullName>
        <description>Text version of the SFDC Sales Manager&apos;s name.  Used in case there is no valid SFDC user record with alias matching the SM Id from the UVX - in this case we just use the SM Name from the UVX.</description>
        <label>Sales Manager</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Manager_Id__c</fullName>
        <description>4-character ID from UVX - from the LEAD column on DCS Code Category 135.</description>
        <formula>Account__r.SalesMgrID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Manager Id (UVX)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <formula>Account__r.SalesMgrName__c</formula>
        <inlineHelpText>Sales Manager from the UVX.</inlineHelpText>
        <label>Sales Manager (UVX)</label>
        <type>Text</type>
    </fields>
    <label>Customer Account Plan</label>
    <nameField>
        <displayFormat>CAP-{MM}-{YYYY}-{000}</displayFormat>
        <label>Customer Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

IC-Test/objects/Customer_Account_Plan_History__c.object
<CustomObject>
    <description>History object to track changes to the CAP</description>
    <fields>
        <fullName>Customer_Account_Plan__c</fullName>
        <label>Customer Account Plan</label>
        <referenceTo>Customer_Account_Plan__c</referenceTo>
        <relationshipLabel>Revision Histories</relationshipLabel>
        <relationshipName>Customer_Account_Plan_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Net_Readiness__c</fullName>
        <label>Net Readiness Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <label>Owner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the SFDC User record corresponding to the Sales Manager from UVX.  Populated on main CAP record by Apex trigger which looks up the User by alias, using the Sales Mgr Id from UVX.</description>
        <label>Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Account_Plan_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMName__c</fullName>
        <description>Text version of the SFDC Sales Manager&apos;s name.  Used in case there is no valid SFDC user record with alias matching the SM Id from the UVX - in this case we just use the SM Name from the UVX.</description>
        <label>Sales Manager</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Manager_Id__c</fullName>
        <label>Sales Manager Id (UVX)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <label>Sales Manager (UVX)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Account Plan History</label>
    <nameField>
        <label>CAP History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Account Plan Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC US IC PROD/src/classes/CustomerAccountPlan_Utilities.cls
public with sharing class CustomerAccountPlan_Utilities
{
	public static void BeforeInsert(List<SObject> updatedMappings)
	{
		CAPGetSalesManager((List<Customer_Account_Plan__c>)updatedMappings);
	}
	
	public static void BeforeUpdate(List<SObject> oldMappings, List<SObject> updatedMappings)
	{
		CAPGetSalesManager((List<Customer_Account_Plan__c>)updatedMappings);
		CloneCAP((List<Customer_Account_Plan__c>)oldMappings);
	}
	
	public static void CAPGetSalesManager(List<Customer_Account_Plan__c> updatedMappings)
	{
		//2013-06-05 K Miller - created

	    // Loop through the incoming records    
	    for (Customer_Account_Plan__c cap : updatedMappings) {
	            
	        string SMId = cap.Sales_Manager_Id__c;
	        
	        if (string.isBlank(SMId) ) {
	           cap.SMLink__c = null;
	           cap.SMName__c = '';        
	        } 
	        else {
	            
	            SMId = 'i' + cap.Sales_Manager_Id__c;                        
	            try {
	                List <User> SM = [select id, name from User where alias = :SMId];  
	                if (SM.isempty()) {
	                    cap.SMLink__c = null; 
	                    cap.SMName__c = cap.Sales_Manager__c + ' (' + SMId + ') - alias not in SFDC';
	                    //cap.SMName__c = cap.Sales_Manager__c;
	                } 
	                else {
	                    cap.SMLink__c = SM[0].Id; 
	                    cap.SMName__c = SM[0].Name;
	                }
	           // } catch (DMLException e){
	            } finally {
	                  //exception
	            }
	        }     
	    }	
	}
	
	public static void CloneCAP(List<Customer_Account_Plan__c> oldMappings)
	{
		Map <String , Schema.SObjectField >capFieldMap = Schema.SObjectType.Customer_Account_Plan__c.fields.getMap();
		Map <String , Schema.SObjectField >historyFieldMap = Schema.SObjectType.Customer_Account_Plan_History__c.fields.getMap();
		Customer_Account_Plan_History__c []clonedCapList = new Customer_Account_Plan_History__c []{};
		for (Customer_Account_Plan__c oldCap : oldMappings) 
		{
			Integer rh = [SELECT COUNT() FROM Customer_Account_Plan_History__c WHERE Customer_Account_Plan__c = :oldCap.Id];
			String rev = String.valueOf(rh + 1);
			Customer_Account_Plan_History__c clonedCap = new Customer_Account_Plan_History__c();
			clonedCap.Name = 'Revision: '+ rev;
			clonedCap.Customer_Account_Plan__c = oldCap.Id;
			clonedCap.Owner_Name__c = oldCap.Owner_Name__c;
			clonedCap.Net_Readiness__c = oldCap.Net_Readiness_Score__c;
			for (String capFieldName :capFieldMap.keySet()) 
			{
				for (String historyFieldName :historyFieldMap.keySet()) 
				{
					String strHist = historyFieldName.substringBeforeLast('__');
					if (capFieldName.startsWith(strHist)&&capFieldName != 'Id'&&capFieldName != 'Name') 
					{
						//System.debug('****** MATCH!!!   HISTORY: ' + historyFieldName + ' ~~~~~~~~~~~~~~ CAPFIELD: ' + capFieldName);
						// Check if history field is actually writeable (controlled by field security)   
						Schema.SObjectField field = historyFieldMap.get(historyFieldName);
						Schema.DescribeFieldResult fieldResult = field.getDescribe();
						if (fieldResult.isUpdateable()) {
							//system.debug('***** UPDATEABLE FIELD!! *****');
							clonedCap.put(historyFieldName, oldCap.get(capFieldName));
						}
						//else system.debug(' **** NOT updateable **** ');
					}
				}
			}
			clonedCapList.add(clonedCap);
		}
		insert clonedCapList;
	}
}