IC-Prod/objects/LicenseAlertConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom settings for sending License Alert Emails. SendTo, CopyTo and EmailTemplate&apos;s DeveloperName. This is used by the AvailableLicenseScheduler apex class.</description>
    <fields>
        <fullName>CopyTo__c</fullName>
        <description>Email address to use for the CC: on the Lilcense alert email. Not required.  If the field is blank, no CC will be added.</description>
        <label>Copy To</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EmailTemplate__c</fullName>
        <description>Enter the Email Template&apos;s DeveloperName to use for sending the License Alert emails.</description>
        <inlineHelpText>Click on &quot;Manage&quot;</inlineHelpText>
        <label>Email Template</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendTo__c</fullName>
        <description>User to Send the Email to.  Will be used in a SOQL query:

User u = [select id, Name from User WHERE IsActive=true AND Email =:SendTo Limit 1];</description>
        <label>Send To</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SenderEmail__c</fullName>
        <description>Who is the email from.  Used in the reply to.</description>
        <label>Sender Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SenderName__c</fullName>
        <description>setSenderDisplayName used in the email.  Shows who the email is from.</description>
        <label>Sender Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>License Alert Configurations</label>
</CustomObject>

IC-Prod/classes/AvailableLicenseScheduler.cls
global class AvailableLicenseScheduler implements Schedulable{
	
	
global void execute(SchedulableContext SC){

LicenseAlertConfig__c la = LicenseAlertConfig__c.getInstance();
String laCopyTo = la.CopyTo__c;
String laEmailTemplate = la.EmailTemplate__c;
String laSenderEmail = la.SenderEmail__c;
String laSenderName = la.SenderName__c;
String laSendTo = la.SendTo__c;

User u = [select id, Name from User WHERE IsActive=true AND Email=:laSendTo Limit 1];
//uid is the target object required - so pick an admin
String uid = u.id;

String[] toAddresses = new String[]{laSendTo};
String[] ccAddresses = new String[] {laCopyTo};
	
 EmailTemplate templateId = [Select id from EmailTemplate where DeveloperName =:laEmailTemplate];
        Messaging.reserveSingleEmailCapacity(2);

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(toAddresses);
        mail.setCcAddresses(ccAddresses);
        mail.setTargetObjectID(uid);
        mail.setTemplateID(templateId.Id);
        mail.setSaveAsActivity(false);
       
        mail.setUseSignature(false);
        mail.setBccSender(false);
        mail.setSenderDisplayName(laSenderName);
        mail.setReplyTo(laSenderEmail);

        System.debug('********* SENDING ************* ' + toAddresses);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
}
}