IC-Test/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AcornRolling12MoSales__c</fullName>
        <description>10/19/2005 - Eli - changed length to 11,2 to match source data from DCS.
5/5/2010:  km - changed Field Name from &quot;Rolling12MonthSales&quot; to &quot;AcornRolling12MoSales__c&quot; and changed length from 11,2 to 11,0.</description>
        <inlineHelpText>Sales and GM information is sourced from Acorn.</inlineHelpText>
        <label>Rolling 12 Month Sales</label>
        <precision>11</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>6</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>NumberofOpportunities__c</fullName>
        <label>Number of Opportunities</label>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>OwnerLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account Owner. Populated via Apex, and then available to use in cross-object formulas to get at Account Owner data.</description>
        <label>Owner Link</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SICIndustryGroupName4__c</fullName>
        <label>UIC Industry</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesOfficeName__c</fullName>
        <label>Sales Office Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingPhone__c</fullName>
        <description>Feb. 22 2005</description>
        <label>Shipping Phone</label>
        <type>Phone</type>
    </fields>
</CustomObject>

SFDC US IC PROD/src/classes/FindNearby.cls
global with sharing class FindNearby {

    public FindNearby(ApexPages.StandardSetController controller) { }

    @RemoteAction
    // Find accounts nearest a geolocation
    global static List<Account> getNearby(String lat, String lon) {

        // If geolocation isn't set, use San Francisco
        if(lat == null || lon == null || lat.equals('') || lon.equals('')) {
            lat = '37.77493';
            lon = '-122.419416';
        }

        // SOQL query to get the nearest warehouses
        String queryString =
            'SELECT Id, Name, Location__Longitude__s, Location__Latitude__s, SalesOfficeName__c, Industry, LastActivityDate, ' +
            	'NumberofOpportunities__c, AcornRolling12MoSales__c, SICIndustryGroupName4__c,' +
                'ShippingStreet , ShippingPhone__c, ShippingCity, RecordType.DeveloperName, OwnerLink__r.Id , OwnerLink__r.Name ' +
            'FROM Account ' +
            'WHERE DISTANCE(Location__c, GEOLOCATION('+lat+','+lon+'), \'mi\') < 200 ' +
            'ORDER BY DISTANCE(Location__c, GEOLOCATION('+lat+','+lon+'), \'mi\') ' +
            'LIMIT 400';

        // Run and return the query results
   
        return(database.Query(queryString));
    }
}