IC-Test/objects/Account_Reassignment__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Statuses will dynamically change depending on stage in the Approval process</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Reassignment</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Account Reassignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Reassignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IC-Test/classes/AcctReassignApprovalControllerTest.cls
@isTest
private class AcctReassignApprovalControllerTest 
{
    static testMethod void TestAcctReassignApprovalController()
    {
    	Account tAcct = UnitTestHelper.createAccount('TestAcct');
    	system.assert(UnitTestHelper.accountSaveSuccess);
    	
    	Account_Reassignment__c tAR = UnitTestHelper.createAR(tAcct);
    	system.assert(UnitTestHelper.arSaveSuccess);
    	
    	AcctReassignApprovalController controller = new AcctReassignApprovalController();

        controller.ArWrappers = new List<AcctReassignApprovalController.ReassignWrap>();
        controller.ArWrappers.add(new AcctReassignApprovalController.ReassignWrap(tAr, true));

        PageReference pageRef = Page.AccountReassignmentApproval;
        Test.setCurrentPage(pageRef);
        Schema.DescribeSObjectResult result = Account_Reassignment__c.SObjectType.getDescribe();
        PageReference arPageRef = new PageReference('/' + result.getKeyPrefix());

    	test.startTest();

    	controller.Approve();
    	system.assertEquals('Pending Approval', tAR.Status__c);

    	controller.Reject();
        system.assert(ApexPages.getMessages().size() > 0);
        controller.RejectReason = 'Not ready for approval';
        controller.Reject();

        controller.redirectToList();

    	test.stopTest();
    }
}