IC-Test/objects/Account_Reassignment__c.object
<CustomObject>
    <fields>
        <fullName>Current_Owner_Manager_Approval__c</fullName>
        <label>Current Owner Manager Approval</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Owner Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner_RSD_Approval__c</fullName>
        <label>Current Owner RSD Approval</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Owner_RSD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Owner RSD</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Owner_Manager_Approval__c</fullName>
        <label>New Owner Manager Approval</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>New_Owner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Owner Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Owner_RSD_Approval__c</fullName>
        <label>New Owner RSD Approval</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>New_Owner_RSD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Owner RSD</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Statuses will dynamically change depending on stage in the Approval process</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Reassignment</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Account Reassignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Reassignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IC-Test/classes/AccountReassignmentBatch.cls
global with sharing class AccountReassignmentBatch implements Database.Batchable<sObject>
{
   global String query { get; set; }
  
   global AccountReassignmentBatch()
   {
        this.query = 'Select a.Status__c, a.OwnerId, a.New_Owner_RSD__c, a.New_Owner_RSD_Approval__c, '
                        + 'a.New_Owner_Manager__c, a.New_Owner_Manager_Approval__c, '
                        + 'a.Current_Owner_RSD__c, a.Current_Owner_RSD_Approval__c, '
                        + 'a.Current_Owner_Manager__c, a.Current_Owner_Manager_Approval__c '
                        + 'FROM Account_Reassignment__c a WHERE Status__c = \'Pending Approval\'';
   }

   global Database.QueryLocator start(Database.BatchableContext BC)
   {
      return Database.getQueryLocator(query);
   }

   global void execute(Database.BatchableContext BC, 
                       List<Account_Reassignment__c> accountReassignments)
   {
      Set<Id> usersToNotify = new Set<Id>();
      for(Account_Reassignment__c accountReassignment : accountReassignments)
      {
            if(accountReassignment.New_Owner_RSD_Approval__c == 'Pending')
            {
            	usersToNotify.add(accountReassignment.New_Owner_RSD__c);
            }
            if(accountReassignment.New_Owner_Manager_Approval__c == 'Pending')
            {
                usersToNotify.add(accountReassignment.New_Owner_Manager__c);
            }
            if(accountReassignment.Current_Owner_RSD_Approval__c == 'Pending')
            {
                usersToNotify.add(accountReassignment.Current_Owner_RSD__c);
            }
            if(accountReassignment.Current_Owner_Manager_Approval__c == 'Pending')
            {
                usersToNotify.add(accountReassignment.Current_Owner_Manager__c);
            }                        
      }
      String emailTemplateName = 'Account_Reassignments_Awaiting_Approval';       
      EmailHelper.sendAccountReassignmentNotificationEmails(usersToNotify, emailTemplateName);
   }

   global void finish(Database.BatchableContext BC)
   {

   }
   
   global static void runBatch() 
   {
        AccountReassignmentBatch batch = new AccountReassignmentBatch();
        Database.executeBatch(batch, 100);
    }
}