IC-Test/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ShipToNumber__c</fullName>
        <label>Ship To</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Users can create these types for prospect accounts.  Once the prospect becomes a customer, this information should be merged with the real customer account.  Only managers and above can merge.</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

IC-Test/objects/Account_Reassignment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Reassignments</relationshipLabel>
        <relationshipName>Account_Reassignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipToNumber__c</fullName>
        <formula>Account__r.ShipToNumber__c</formula>
        <label>Ship To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Statuses will dynamically change depending on stage in the Approval process</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Reassignment</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Account Reassignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Reassignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IC-Test/classes/AccountReassignment_Tests.cls
@isTest
public with sharing class AccountReassignment_Tests
{
	public static testmethod void testSetNewOwnerForProspectAccountsOnApproved()
	{
		RecordType accountRecordTypeShipTo = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Prospect' AND IsActive = true LIMIT 1];
		System.assert(accountRecordTypeShipTo != null, 'No Prospect Record Type found.');
		
		List<User> testUsers = [SELECT Id, Name FROM User WHERE IsActive = true LIMIT 2];
		
		Account a = new Account(
			  Name = 'testAccount'
			, RecordTypeId = accountRecordTypeShipTo.Id
			, ShipToNumber__c = '125'
			, OwnerId = testUsers[0].Id
		);
		Database.insert(a);
		
		Account_Reassignment__c ar = new Account_Reassignment__c(
			  Account__c = a.Id
			, Status__c = 'Pending Approval'
			, Current_Owner__c = testUsers[0].Id
			, New_Owner__c = testUsers[1].Id
		);
		Database.insert(ar);
		
		ar.Status__c = 'Approved';
		Database.update(ar);
		
		Account refreshedAccount = [SELECT Id, OwnerId FROM Account WHERE Id = :a.Id LIMIT 1];
		
		System.assertEquals(ar.New_Owner__c, refreshedAccount.OwnerId, 'Owner should have been changed.');
	}
}