IC-Test/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AcornRolling12MoSales__c</fullName>
        <description>10/19/2005 - Eli - changed length to 11,2 to match source data from DCS.
5/5/2010:  km - changed Field Name from &quot;Rolling12MonthSales&quot; to &quot;AcornRolling12MoSales__c&quot; and changed length from 11,2 to 11,0.</description>
        <inlineHelpText>Sales and GM information is sourced from Acorn.</inlineHelpText>
        <label>Rolling 12 Month Sales</label>
        <precision>11</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CustomerShipTo__c</fullName>
        <description>9 digit external ID corresponding to unique id from DCS: 6 digits for bill-to, plus 3 digits for ship-to. Populated via integration - cannot be a formula field because formulas cannot be external Ids.</description>
        <externalId>true</externalId>
        <inlineHelpText>9 digit ID corresponding to unique id from DCS: 6 digits for bill-to, plus 3 digits for ship-to.  Populated via integration only, non-editable.</inlineHelpText>
        <label>Customer Ship To</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ShipToNumber__c</fullName>
        <label>Ship To</label>
        <length>3</length>
        <type>Text</type>
    </fields>
</CustomObject>

IC-Test/objects/Account_Reassignment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Reassignments</relationshipLabel>
        <relationshipName>Account_Reassignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Manager_Approval__c</fullName>
        <label>Current Owner Manager Approval</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Manager_Approved_Date__c</fullName>
        <label>Current Owner Manager Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Owner Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner_RSD_Approval__c</fullName>
        <label>Current Owner RSD Approval</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Owner_RSD_Approved_Date__c</fullName>
        <label>Current Owner RSD Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Current_Owner_RSD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Owner RSD</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner_RVP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Owner RVP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Role__c</fullName>
        <formula>Account__r.Owner.UserRole.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Owner Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_in_Pending_Approval_Status__c</fullName>
        <formula>IF( ISPICKVAL(Status__c,&quot;Drafted&quot;), 0,
IF( ISPICKVAL(Status__c, &quot;Pending Approval&quot;), TODAY() - Pending_Approval_Date__c,
IF( ISPICKVAL(Status__c, &quot;Approved&quot;),  Approved_Date__c - Pending_Approval_Date__c, 
IF( ISPICKVAL(Status__c, &quot;Rejected&quot;),  Rejected_Date__c - Pending_Approval_Date__c,
0
))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days in Pending Approval Status</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Owner_Manager_Approval__c</fullName>
        <label>New Owner Manager Approval</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>New_Owner_Manager_Approved_Date__c</fullName>
        <label>New Owner Manager Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>New_Owner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Owner Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Owner_RSD_Approval__c</fullName>
        <label>New Owner RSD Approval</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>New_Owner_RSD_Approved_Date__c</fullName>
        <label>New Owner RSD Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>New_Owner_RSD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Owner RSD</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Owner_RVP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Owner RVP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Owner_Role__c</fullName>
        <formula>New_Owner__r.UserRole.Name</formula>
        <label>New Owner Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Reassignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pending_Approval_Date__c</fullName>
        <description>Date that the user first submits request for approval</description>
        <label>Pending Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <label>Rejection Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ShipToNumber__c</fullName>
        <formula>Account__r.ShipToNumber__c</formula>
        <label>Ship To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Statuses will dynamically change depending on stage in the Approval process</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Reassignment</label>
    <nameField>
        <displayFormat>AR-{0000000000}</displayFormat>
        <label>Account Reassignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Reassignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC US IC PROD/src/classes/AcctReassignApprovalController.cls
public with sharing class AcctReassignApprovalController 
{
    public List<ReassignWrap> ArWrappers { get; set; }
    public string RejectReason { get; set; }
    public Boolean ShowRejectReason { get; set; }
    public Boolean UpdateSuccess { get; set; }
    
	static final string statusPending = 'Pending Approval';
    static final string statusManagerApproval = 'Pending';
    static final string statusApprove = 'Approved';
    static final string statusReject = 'Rejected';
    
	private string newStatus;

    public AcctReassignApprovalController()
    {
        Id userId = UserInfo.getUserId();
        ArWrappers = new List<ReassignWrap>();
        //ErikH 2014.01.30 - Removed Effective Date from controller and apex page. No longer a needed field.
		//WBR Adding Owner.User_District__c by request from Rachel Kanter
        for (Account_Reassignment__c ar : [Select Account__c, Name, CreatedById, Current_Owner__c, Current_Owner__r.User_District__c
                                                , Current_Owner_Manager__c, Current_Owner_RSD__c, New_Owner__r.User_District__c
                                                , Current_Owner_Manager_Approval__c, Days_in_Pending_Approval_Status__c
                                                , New_Owner__c, New_Owner_Role__c, New_Owner_Manager__c, New_Owner_Manager_Approval__c
                                                , Current_Owner_RVP__c, New_Owner_RVP__c
												, Pending_Approval_Date__c, Status__c, Account__r.CustomerShipTo__c
                                                , Account__r.Name, Account__r.ShippingCity, Account__r.ShippingStateCode, Account__r.ShippingCountryCode
                                                , Account__r.AcornRolling12MoSales__c, Current_Owner_Role__c, New_Owner_RSD__c
												, Account__r.ShipToNumber__c
                                        FROM    Account_Reassignment__c
                                        WHERE   Status__c =: statusPending
                                        AND     ((Current_Owner_Manager_Approval__c =: statusManagerApproval 	AND Current_Owner_Manager__c =: userId)
										 OR		  (Current_Owner_RSD_Approval__c =: statusManagerApproval 		AND (Current_Owner_RSD__c =: userId OR Current_Owner_RVP__c =: userId))
										 OR		  (New_Owner_Manager_Approval__c =: statusManagerApproval 		AND New_Owner_Manager__c =: userId)
										 OR 	  (New_Owner_Manager_Approval__c =: statusManagerApproval		AND (New_Owner_RSD__c =: userId OR New_Owner_RVP__c =: userId)))])
        {
            ReassignWrap rw = new ReassignWrap(ar, false);
            ArWrappers.add(rw);
        }
        UpdateSuccess = false;
    }
    
    public PageReference Reject()
    {
        newStatus = statusReject;
        if (RejectReason == null)
        {
            // show reject reason textbox
            ShowRejectReason = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Please enter a rejection reason below'));
        }
        else
        {
            ShowRejectReason = false;
            processSelected();
        }
        return null;
    }
	
	public PageReference RejectNew()
	{
		/*if (RejectReason == null)
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Please enter a rejection reason below'));
			return null;
		}*/
		if (!hasSelectedNotYetUpdated()) { return null; }
		
		newStatus = statusReject;
		processSelected();
		displayPopup = false;
		return null;
	}
	
	public PageReference CancelReject()
	{
		displayPopup = false;
		return null;
	}

    public PageReference Approve()
    {
        newStatus = statusApprove;
        processSelected();
        return null;
    }
    
    public PageReference redirectToList() 
    {
        Schema.DescribeSObjectResult result = Account_Reassignment__c.SObjectType.getDescribe();
    
        PageReference pageRef = new PageReference('/' + result.getKeyPrefix());
        pageRef.setRedirect(true);
        return pageRef;
    }
	
	private Boolean hasSelectedNotYetUpdated()
	{
		for(ReassignWrap wrap: ArWrappers)
		{
			if (wrap.Selected == true && wrap.Updated == false) { return true; }
		}
		return false;
	}
	
    private void processSelected()
    {
        // create list of ARs to be populated with selected row objects
        List<Account_Reassignment__c> updateARs = new List<Account_Reassignment__c>();
		Id userId = UserInfo.getUserId();
		
        // cycle through list of cContacts and will check to see if the selected property is set to true, if it is we add the Contact to the selectedContacts list
        for(ReassignWrap wrap: ArWrappers) 
        {
            if (wrap.Selected == true && wrap.Updated == false) 
            {
                if (wrap.AcctReassign.Current_Owner_Manager__c == userId)
				{
					wrap.AcctReassign.Current_Owner_Manager_Approval__c = newStatus;
                	wrap.AcctReassign.Current_Owner_Manager_Approved_Date__c = Datetime.now();
				}
				
				if (wrap.AcctReassign.Current_Owner_RSD__c == userId || wrap.AcctReassign.Current_Owner_RVP__c == userId)
				{
					wrap.AcctReassign.Current_Owner_RSD_Approval__c = newStatus;
					wrap.AcctReassign.Current_Owner_RSD_Approved_Date__c = Datetime.now();
				}
				
				if (wrap.AcctReassign.New_Owner_Manager__c == userId)
				{
					wrap.AcctReassign.New_Owner_Manager_Approval__c = newStatus;
					wrap.AcctReassign.New_Owner_Manager_Approved_Date__c = Datetime.now();
				}
				
				if (wrap.AcctReassign.New_Owner_RSD__c == userId || wrap.AcctReassign.New_Owner_RVP__c == userId)
				{
					wrap.AcctReassign.New_Owner_RSD_Approval__c = newStatus;
					wrap.AcctReassign.New_Owner_RSD_Approved_Date__c = Datetime.now();
				}
				
				if (newStatus == statusReject)
				{
					wrap.AcctReassign.Rejection_Reason__c = RejectReason;
				}
				
				wrap.BackgroundColor = newStatus == statusApprove ? '#D6FFAD' : '#FFC2B2';  // ? #light green : #light red
				wrap.Updated = true;
				updateARs.add(wrap.AcctReassign);
            }
        }

        // Now we have our list of selected contacts and can perform any type of logic we want, sending emails, updating a field on the Contact, etc
        System.debug('These are the selected ARs...' + updateARs);
        Database.Saveresult[] saveResults = Database.update(updateARs);
        UpdateSuccess = true;
        for (Database.SaveResult sr: saveResults)
        {
            if (!sr.isSuccess())
            {
                UpdateSuccess = false;
            }
        }
    }

    public class ReassignWrap
    {
        public Account_Reassignment__c AcctReassign { get; set; }
        public Boolean Selected { get; set; }
		public String BackgroundColor { get; Set; }
		public Boolean Updated { get; Set; }
        
        public ReassignWrap(Account_Reassignment__c ar, Boolean sel)
        {
            AcctReassign = ar;
            Selected = sel;
			BackgroundColor = '';
			Updated = false;
        }
    }
	
	public boolean displayPopup {get; set;}     
    
    public void closePopup() {        
        displayPopup = false;    
    }     
    public void showPopup() {        
        if (!hasSelectedNotYetUpdated()) { return; }
		displayPopup = true;    
    }
}