IC-Test/objects/CoachingWorksheet__c.object
<CustomObject>
    <fields>
        <fullName>DirectReportNm__c</fullName>
        <description>Used behind the scenes, for example by Apex in formatting screen error messages.</description>
        <formula>DirectReport__r.FirstName + &quot; &quot; + DirectReport__r.LastName</formula>
        <label>Direct Report Name - No Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DirectReport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Direct Report</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DirectReport</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OwnerLink__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Link</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CoachingOwnerLink</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SessionDate__c</fullName>
        <inlineHelpText>The coaching observation date that this worksheet is for</inlineHelpText>
        <label>Session Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Draft: Not yet released for review by Direct Report.
Direct Report Review: Direct Report needs to review &amp; submit for approval
Feedback Received: Direct Report has submitted for approval. Now waiting for manager review.
Manager Approved: Complete.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Report Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Coaching Worksheet</label>
    <nameField>
        <displayFormat>CW-{0000}</displayFormat>
        <label>Coaching ID#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coaching Worksheets</pluralLabel>
    <recordTypes>
        <fullName>Draft</fullName>
        <active>true</active>
        <description>For Coaching Worksheets in New or Draft Status - for page layout differentiation</description>
        <label>1. Draft</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

IC-Test/classes/CoachingWorksheet_Utilities.cls
public with sharing class CoachingWorksheet_Utilities
{
	public static void PreventDuplicateCoachingWorksheets(List<SObject> objects)
	{
		//Check for duplicates - can only have one Session Date per Direct Report
		//If count is greater than 1 there is a duplicate.  Need to use "After" insert so it will include the current record.

		//2012-09-04 K Miller - created

		// Loop through the incoming records
		for (CoachingWorksheet__c c : (List<CoachingWorksheet__c>)objects) {

			system.debug('DR firstName: ' + c.DirectReportNm__c);

			Integer i = [ select count() from CoachingWorksheet__c where SessionDate__c = :c.SessionDate__c
		            and DirectReport__c = :c.DirectReport__c ];
			if (i > 1) {
				c.SessionDate__c.addError('' + c.DirectReportNm__c + ' already has a worksheet for this Session Date.');
			}
		}
	}
	
	private static void UpdateCoachingWorksheet(List<SObject> objects, Boolean bInsert)
	{
		//2012-08-29 K Miller - created

	    // Loop through the incoming records
	    for (CoachingWorksheet__c c : (List<CoachingWorksheet__c>)objects	) {
	    
	        // New record - we assume the manager is the owner
	        if (bInsert) {
	               c.Manager__c = c.OwnerID;
	        }
	        
	        // After draft, ownership moves to the Direct Report
	        if (c.Status__c != 'Draft') {
	              c.OwnerID = c.DirectReport__c;
	        }
	        
	        // Has Owner changed?  If so update the link
	        if (c.OwnerID != c.OwnerLink__c) {
	         c.OwnerLink__c = c.OwnerId;
	        }
	    }
	}
	
	public static void BeforeInsert(List<SObject> objects)
	{
		UpdateCoachingWorksheet(objects, true);
	}
	
	public static void BeforeUpdate(List<SObject> objects)
	{
		UpdateCoachingWorksheet(objects, false);
	}
	
}