IC-Test/objects/EmailResultSummary__c.object
<CustomObject>
    <label>Email Result Summary</label>
    <nameField>
        <label>Email Result Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Result Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IC-Test/objects/xtma_Individual_Email_Result__c.object
<CustomObject>
    <fields>
        <fullName>EmailResultSummary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Email Result Summary</label>
        <referenceTo>EmailResultSummary__c</referenceTo>
        <relationshipLabel>Individual Email Results</relationshipLabel>
        <relationshipName>IndividualEmailResults</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Individual Email Result</label>
    <nameField>
        <label>Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individual Email Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC US IC PROD/src/classes/xtmaIndividualEmailResult_Utilities.cls
public with sharing class xtmaIndividualEmailResult_Utilities
{
	private static void UpdateEmailResultSummaryTotals(List<xtma_Individual_Email_Result__c> objects, Boolean bInsert)
	{
			// Add IER records to ERS records
	    if( bInsert ) {
			Set<Id> ids = new Set<Id>();
			for(xtma_Individual_Email_Result__c x : objects)
				ids.add(x.Id);
	                        
	        EmailSummaryController.updateEmailResultSummaryRecord( ids );
	        
	    }
	    
	    // Create set of unique ERS records to update
	    Set<Id> ersIds = new Set<Id>();
	    for( xtma_Individual_Email_Result__c emailResult : objects ) {
	        
	        if( emailResult.emailResultSummary__c != null ) ersIds.add( emailResult.emailResultSummary__c );
	        
	    }
	    
	    if( ersIds.size() > 0 ) {
	        
	        List<Id> ids = new List<Id>();
	        for( Id ersId : ersIds ) {
	            ids.add( ersId );
	        }
	        
	        EmailSummaryController.updateEmailResultSummaryTotals( ids );
	        
	    }
	}
	
	public static void AfterInsert(List<SObject> objects)
	{
		UpdateEmailResultSummaryTotals((List<xtma_Individual_Email_Result__c>)objects, true);
	}
	
	public static void AfterUpdate(List<SObject> objects)
	{
		UpdateEmailResultSummaryTotals((List<xtma_Individual_Email_Result__c>)objects, false);
	}
}